#!/usr/bin/env python3
"""
make_cycle.py -- regenerate assets/ecr88/cycle.json from the asset's own geometry.

The work cycle is solved, not hand-typed: every keyframe that touches something is an IK
solution (sil/ik.py) aimed at the firmware's frames in the expanded URDF. Re-run this whenever
joint limits, the tool chain or the fork geometry change, then rebuild the scene
(animate_cycle.py refuses keyframes outside the USD joint limits).

    xacro assets/ecr88/urdf/ecr88.urdf.xacro -o build/ecr88.urdf
    python3 scripts/make_cycle.py --urdf build/ecr88.urdf

Keyframes (firmware order): raised home -> approach (panel_pick_approach_link) -> contact
(panel_top_link) -> grip -> lift past the Placing clearance gates -> slew -> hover -> set down on
the row -> release -> retract -> slew back -> home.
"""
import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
from sil import ik  # noqa: E402
from sil.urdf_fk import UrdfModel  # noqa: E402

PLACE_TCP = np.array([4.712, 4.5, -0.207])   # working-row set-down point used by the site and camera study
OUTP_LINK_CLEAR = 1.0 + 0.05                  # SysPar.m:264 OutpLinkHgtToClearPanelStack, + margin
TOOL_SWING_HGT = 0.8 + 0.05                   # MdlApp.c:13060 commanded tool height for swing, + margin


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--urdf", type=Path, default=REPO / "build" / "ecr88.urdf")
    ap.add_argument("--out", type=Path, default=REPO / "assets" / "ecr88" / "cycle.json")
    args = ap.parse_args()
    m = UrdfModel(args.urdf)
    q = lambda d: ik.q_of(d["swing"], d["boom"], d["arm"], d["bucket"])
    tcp = lambda d: m.fk("contact_surface_link", q(d))
    outp = lambda d: m.fk("output_link", q(d))
    UP = np.array([0.0, 0.0, 1.0])
    kf, notes = {}, []

    def need(name, res, tol_mm=1.0):
        if res is None or res[1] * 1000 > tol_mm:
            raise SystemExit(f"[cycle] {name}: no solution within {tol_mm} mm ({None if res is None else res[1]*1000:.1f} mm)")
        notes.append(f"{name}: {res[1]*1000:.2f} mm, tool-axis error {res[2]:.2f} deg")
        return res[0]

    Tpt, Tap = m.fk("panel_top_link", {}), m.fk("panel_pick_approach_link", {})
    n = Tpt[:3, 2]
    kf["contact"] = need("contact", ik.solve(m, Tpt[:3, 3], n))
    kf["approach"] = need("approach", ik.solve(m, Tap[:3, 3], n))

    def pitch_dir(deg):
        return np.array([math.sin(math.radians(deg)), 0.0, math.cos(math.radians(deg))])

    p_ref = math.degrees(math.atan2(n[0], n[2]))
    for dz in np.arange(0.3, 3.0, 0.1):
        hit = None
        for pit in np.linspace(p_ref, 0.0, 9):
            r = ik.solve(m, Tpt[:3, 3] + np.array([0, 0, dz]), pitch_dir(pit))
            if r and r[1] < 0.005:
                sol = dict(r[0], swing=kf["contact"]["swing"])
                if outp(sol)[2, 3] > OUTP_LINK_CLEAR and tcp(sol)[2, 3] > TOOL_SWING_HGT:
                    hit = r
                    break
        if hit:
            kf["lift"] = dict(hit[0], swing=kf["contact"]["swing"])
            notes.append(f"lift: {dz:.1f} m above the face centre; output link {outp(kf['lift'])[2,3]:.2f} m, tool {tcp(kf['lift'])[2,3]:.2f} m")
            break
    else:
        raise SystemExit("[cycle] no lift pose clears the stack")

    raise_pose = None
    for z in np.arange(1.6, 0.4, -0.1):
        for x in np.arange(4.4, 2.8, -0.2):
            r = ik.solve(m, np.array([x, m.fk("contact_surface_link", ik.q_of(0, 0, 0, 0))[1, 3], z]), UP, swing_deg=0.0)
            if r and r[1] < 0.005:
                raise_pose = r
                break
        if raise_pose:
            break
    kf["home"] = need("home", raise_pose, tol_mm=5)
    kf["set_down"] = need("set down", ik.solve(m, PLACE_TCP, UP))
    kf["hover"] = need("hover", ik.solve(m, PLACE_TCP + np.array([0, 0, 0.6]), UP))
    kf["slew"] = dict(kf["lift"], swing=kf["set_down"]["swing"])

    r2 = lambda d: {k: round(float(d[k]), 2) for k in ("swing", "boom", "arm", "bucket")}
    seq = [("home (raised)", 0, "home"), ("approach", 60, "approach"), ("contact", 110, "contact"),
           ("grip", 150, "contact"), ("lift clear", 190, "lift"), ("slew", 270, "slew"), ("hover", 340, "hover"),
           ("set down", 400, "set_down"), ("release", 440, "set_down"), ("retract", 480, "hover"),
           ("slew back", 540, "lift"), ("home (raised)", 600, "home")]
    old = json.loads(args.out.read_text(encoding="utf-8")) if args.out.is_file() else {}
    doc = {
        "_doc": ["GENERATED by scripts/make_cycle.py from " + str(args.urdf.name) + " - do not hand-edit keyframes; re-run the script.",
                 "Angles in degrees, firmware joint convention (== URDF).",
                 "Solve residuals: " + "; ".join(notes)],
        "keyframes": [dict(name=nm, frame=fr, **r2(kf[k])) for nm, fr, k in seq],
        "windows": old.get("windows", {}),
    }
    args.out.write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    for line in notes:
        print("[cycle]", line)
    print("[cycle] wrote", args.out)


if __name__ == "__main__":
    main()
