#!/usr/bin/env python3
"""
build.py -- compile the X1Exc firmware (MdlApp) into a host shared library for SIL.

READS X1Exc, NEVER WRITES IT. Every output goes to <xpanner-sim>/build/sil/.

WHAT IT PRODUCES
    build/sil/libx1exc_sil.so   MdlApp.c + _sharedutils/*.c + a generated signal table
    build/sil/sil_table.c       the generated table (kept for inspection)
    build/sil/manifest.json     X1Exc commit, compiler, leaf counts, enums, inhibit bits

THE SIGNAL TABLE, AND WHY THE COMPILER CHECKS IT
    ExtU_MdlApp_T alone has 91 fields and several nested bus types; ParLocal_t is bigger.
    Hand-writing ctypes structures for that is how a SIL harness ends up feeding the
    wrong byte to the right-looking name. So the headers are parsed, every leaf field is
    flattened to a dotted path ("tarPanelData.row1Id", "parKin.lenArm"), and each leaf is
    emitted with offsetof() + a _Static_assert on its sizeof. If the parser ever
    misreads a type, the table does not compile. (The first thing this caught while
    being written: TarPanelData_t.row1Id is uint32, not the uint8 the analysis said.)

WORD SIZE
    The ERT code was generated for a 32-bit target and #errors if long is not 32-bit.
    rtwtypes.h maps every fixed-width type to char/short/int and no generated .c uses
    long or ulong_T, so the guard is the only thing that sees the difference. A forced
    include redefines LONG_MAX/ULONG_MAX for the guard only. The sanctioned fix is
    "Enable portable word sizes" at code generation time; ask David if this ever matters.

USAGE
    python3 sil/build.py [--x1exc /home/ubuntu/jude/X1Exc] [--cc gcc]
"""
import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_X1EXC = Path(os.environ.get("X1EXC_DIR", REPO.parent / "X1Exc"))
OUT = REPO / "build" / "sil"

PRIM = {  # rtwtypes name -> (type code, size in bytes)
    "int8_T": ("b", 1), "uint8_T": ("B", 1), "boolean_T": ("?", 1), "char_T": ("b", 1),
    "int16_T": ("h", 2), "uint16_T": ("H", 2),
    "int32_T": ("i", 4), "uint32_T": ("I", 4), "int_T": ("i", 4), "uint_T": ("I", 4),
    "real32_T": ("f", 4), "real64_T": ("d", 8), "real_T": ("d", 8), "time_T": ("d", 8),
}
ROOTS = [  # (prefix, C type, C object)
    ("u", "ExtU_MdlApp_T", "MdlApp_U"),
    ("y", "ExtY_MdlApp_T", "MdlApp_Y"),
    ("par", "ParLocal_t", "parLocalTest"),
]

SHIM = """/* generated by sil/build.py -- see WORD SIZE in its docstring */
#include <limits.h>
#undef ULONG_MAX
#undef LONG_MAX
#define ULONG_MAX 0xFFFFFFFFUL
#define LONG_MAX  0x7FFFFFFFL
"""


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def parse_headers(header_files):
    structs, enums = {}, {}
    for hf in header_files:
        t = strip_comments(hf.read_text(encoding="latin-1"))
        for m in re.finditer(r"typedef\s+struct\s*\w*\s*\{(.*?)\}\s*(\w+)\s*;", t, re.S):
            body, name = m.group(1), m.group(2)
            fields = []
            for stmt in body.split(";"):
                stmt = " ".join(stmt.split())
                if not stmt or ":" in stmt:  # bitfields live only in DW, never in U/Y/par
                    continue
                fm = re.match(r"^(?:const )?(\w+) (\w+)((?:\[\d+\])*)$", stmt)
                if not fm:
                    # e.g. the nested union in rt_nonfinite.h. Harmless unless a root
                    # actually reaches this type, and flatten() refuses loudly if it does.
                    fields = None
                    break
                dims = [int(d) for d in re.findall(r"\[(\d+)\]", fm.group(3))]
                fields.append((fm.group(1), fm.group(2), dims))
            structs[name] = fields
        for m in re.finditer(r"typedef\s+enum\s*\{(.*?)\}\s*(\w+)\s*;", t, re.S):
            vals, nxt = {}, 0
            for item in m.group(1).split(","):
                item = item.strip()
                if not item:
                    continue
                if "=" in item:
                    k, v = [x.strip() for x in item.split("=", 1)]
                    v = re.sub(r"\(\w+\)", "", v)  # strip casts
                    nxt = int(v.rstrip("uUlL"), 0)
                else:
                    k = item
                vals[k] = nxt
                nxt += 1
            enums[m.group(2)] = vals
    return structs, enums


def flatten(structs, enums, ctype, path=""):
    """Yield (dotted path, C designator, type code, element count, element C type)."""
    if structs[ctype] is None:
        raise SystemExit(f"[build] {ctype} (reached via {path or 'root'}) has a body this parser cannot read")
    for ftype, name, dims in structs[ctype]:
        count = 1
        for d in dims:
            count *= d
        p = f"{path}.{name}" if path else name
        if ftype in PRIM or ftype in enums:
            code = PRIM[ftype][0] if ftype in PRIM else "e"
            yield p, p, code, count, ftype
        elif ftype in structs:
            if dims:
                if len(dims) != 1:
                    raise SystemExit(f"[build] multi-dim struct array {p} not supported")
                for i in range(dims[0]):
                    yield from flatten(structs, enums, ftype, f"{p}[{i}]")
            else:
                yield from flatten(structs, enums, ftype, p)
        else:
            raise SystemExit(f"[build] unknown type {ftype} at {p}")


def inhibit_bits(mdlapp_c):
    t = mdlapp_c.read_text(encoding="latin-1")
    bits = {m.group(1): int(m.group(2)) for m in
            re.finditer(r"'\s*(BIT_\w+)\s*=\s*bitshift\(uint32\(1\),\s*(\d+)\)", t)}
    masks = {}
    for mask in ("AUTO_INHIBIT_MASK", "CALIB_INHIBIT_MASK"):
        names = re.findall(mask + r"\s*=\s*bitor\(" + mask + r",\s*(BIT_\w+)\)", t)
        masks[mask] = {"bits": sorted(set(names), key=lambda n: bits[n]),
                       "value": sum(1 << bits[n] for n in set(names))}
    return bits, masks


def chart_state_names(mdlapp_c, chart_tag):
    """MdlApp_IN_* constants of one chart: index -> state name. The generated code emits
    a block per chart headed /* Named constants for Chart: '<Sx>/Name' */."""
    t = mdlapp_c.read_text(encoding="latin-1")
    i = t.find(f"/* Named constants for Chart: '{chart_tag}' */")
    if i < 0:
        raise SystemExit(f"[build] no named-constant block for {chart_tag}")
    j = t.find("/* Named constants", i + 10)
    names = {}
    # Long names get a truncated prefix (MdlA_IN_..., MdlAp_IN_...); names that collide
    # across charts get a 4-char random suffix (_gmki, _a01c). "_save" is a real word here.
    for m in re.finditer(r"#define Mdl\w*?_IN_(\w+)\s+\(\(uint8_T\)(\d+)U\)", t[i:j]):
        name = m.group(1)
        sfx = re.search(r"_([a-z0-9]{4})$", name)
        if sfx and sfx.group(1) != "save":
            name = name[:sfx.start()]
        idx = int(m.group(2))
        if idx in names:
            raise SystemExit(f"[build] {chart_tag}: state index {idx} defined twice ({names[idx]}, {name})")
        names[idx] = name
    if sorted(names) != list(range(1, len(names) + 1)):
        raise SystemExit(f"[build] {chart_tag}: state indices not contiguous: {sorted(names)}")
    names[0] = "NO_ACTIVE_CHILD"
    return names


# Internal signals exposed READ-ONLY through generated getters. Several are 1-bit
# bitfields in MdlApp_B/DW (offsetof cannot address them), so each is a C function.
# Names are the generated ones; a rename upstream breaks the compile, not a test.
INTERNALS = [
    # (getter suffix, C type returned, expression)
    ("main_chart_state",   "unsigned int", "MdlApp_DW.bitsForTID0.is_c75_MdlApp"),
    ("calib_chart_state",  "unsigned int", "MdlApp_DW.bitsForTID0.is_c11_MdlApp"),
    ("positioning_step",   "int",          "(int)MdlApp_B.positioningStep"),
    ("picking_step",       "int",          "(int)MdlApp_B.pickingStep"),
    ("placing_step",       "int",          "(int)MdlApp_B.placingStep"),
    ("swing_init",         "unsigned int", "MdlApp_B.bitsForTID0.isJntAngSwingInit"),
    ("all_cups_in_contact","unsigned int", "MdlApp_B.bitsForTID0.areAllSuctionCupsInContact"),
    ("was_panel_attached", "unsigned int", "(unsigned int)MdlApp_DW.wasPanelAttached"),
    ("was_panel_detached", "unsigned int", "MdlApp_DW.bitsForTID0.wasPanelDetached"),
    ("low_vertical_accuracy", "unsigned int", "MdlApp_DW.bitsForTID0.lowVerticalAccuracyState"),
    ("enh_local_main_e",   "float", "MdlApp_B.enh_LocalMain[0]"),
    ("enh_local_main_n",   "float", "MdlApp_B.enh_LocalMain[1]"),
    ("enh_local_main_h",   "float", "MdlApp_B.enh_LocalMain[2]"),
    ("enh_local_aux_e",    "float", "MdlApp_B.enh_LocalAux[0]"),
    ("enh_local_aux_n",    "float", "MdlApp_B.enh_LocalAux[1]"),
    ("enh_local_aux_h",    "float", "MdlApp_B.enh_LocalAux[2]"),
]


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--x1exc", type=Path, default=DEFAULT_X1EXC)
    ap.add_argument("--cc", default=os.environ.get("CC", "gcc"))
    args = ap.parse_args()

    gen = args.x1exc / "Asw" / "GeneratedCode"
    rtw, shared = gen / "MdlApp_ert_rtw", gen / "slprj" / "ert" / "_sharedutils"
    mdlapp_c = rtw / "MdlApp.c"
    if not mdlapp_c.is_file():
        raise SystemExit(f"[build] {mdlapp_c} not found (set --x1exc or X1EXC_DIR)")
    OUT.mkdir(parents=True, exist_ok=True)

    structs, enums = parse_headers(sorted(shared.glob("*.h")) + [rtw / "MdlApp.h"])
    bits, masks = inhibit_bits(mdlapp_c)
    literals = [int(x) for x in re.findall(r"\(\(uint32_T\)status\)\s*&\s*\(\(uint32_T\)(\d+)U\)",
                                           mdlapp_c.read_text(encoding="latin-1"))]
    # The generated code tests AUTO first (MdlApp.c ~39675) then CALIB (~39679).
    for mask, lit in zip(("AUTO_INHIBIT_MASK", "CALIB_INHIBIT_MASK"), literals):
        if lit != masks[mask]["value"]:
            raise SystemExit(f"[build] {mask} from comments {masks[mask]['value']} != literal in code {lit}")
    if len(literals) < 2:
        raise SystemExit(f"[build] expected AUTO and CALIB mask literals in MdlApp.c, found {literals}")
    chart_states = {"main": chart_state_names(mdlapp_c, "<S5>/Chart"),
                    "calib": chart_state_names(mdlapp_c, "<S20>/CalibStepMgr")}
    # Chart state names are NOT the CalibStep enum names (the chart's entry actions write
    # calibStep = CalibStep.X; its own state names differ: Standby vs CalibStandby, and two
    # upstream spellings ForkUpPntFront_stb / SwingPose1_LeBreak). Record, do not fail:
    # y.calibStep is the authoritative progress signal, the chart state is a debug aid.
    calib_name_mismatch = sorted(set(chart_states["calib"].values()) - set(enums["CalibStep"]) - {"NO_ACTIVE_CHILD"})

    (OUT / "wordsize_shim.h").write_text(SHIM)
    lines = [
        "/* GENERATED by sil/build.py from X1Exc headers. Do not edit. */",
        "#include <stddef.h>", "#include <fenv.h>", "#include <xmmintrin.h>", '#include "MdlApp.h"', "",
        "typedef struct { const char *path; unsigned char base; unsigned char type;",
        "                 unsigned int count; unsigned long offset; unsigned int elem_size; } sil_sig_t;",
        "",
        "const sil_sig_t sil_signals[] = {",
    ]
    asserts, n_by_root = [], {}
    for ri, (prefix, ctype, obj) in enumerate(ROOTS):
        n = 0
        for path, desig, code, count, ftype in flatten(structs, enums, ctype):
            size = PRIM[ftype][1] if ftype in PRIM else 4
            lines.append(f'  {{"{prefix}.{path}", {ri}, \'{code}\', {count}u, '
                         f"offsetof({ctype}, {desig}), {size}u}},")
            asserts.append(f"_Static_assert(sizeof((({ctype}*)0)->{desig}) == {count * size}u, "
                           f'"{prefix}.{path}");')
            n += 1
        n_by_root[prefix] = n
    lines += ["};", "const unsigned int sil_signal_count = sizeof(sil_signals)/sizeof(sil_signals[0]);", ""]
    lines += [f"_Static_assert(sizeof({e}) == 4u, \"enum {e} is not int-sized\");" for e in enums]
    lines += asserts + [
        "",
        "void *sil_base(unsigned int b) {",
        "  switch (b) { case 0: return &MdlApp_U; case 1: return &MdlApp_Y; case 2: return &parLocalTest; }",
        "  return 0;",
        "}",
        "unsigned long sil_base_size(unsigned int b) {",
        "  switch (b) { case 0: return sizeof(MdlApp_U); case 1: return sizeof(MdlApp_Y); case 2: return sizeof(parLocalTest); }",
        "  return 0;",
        "}",
        "",
        "/* Floating-point environment guard. A physics runtime in the same process (Isaac Sim /",
        "   PhysX) may enable flush-to-zero / denormals-are-zero or change rounding; that would",
        "   silently change the firmware's filters. 0 = OK, else the offending MXCSR bits | 1<<31",
        "   when rounding is not to-nearest. */",
        "unsigned int sil_fp_env_violation(void) {",
        "  unsigned int bad = _mm_getcsr() & 0x8040u;",
        "  if (fegetround() != FE_TONEAREST) bad |= 0x80000000u;",
        "  return bad;",
        "}",
        "",
    ] + [f"{ctype} sil_int_{name}(void) {{ return {expr}; }}" for name, ctype, expr in INTERNALS]
    table_c = OUT / "sil_table.c"
    table_c.write_text("\n".join(lines) + "\n")

    # -w silences the generated code's noise, but these two stay errors: a regeneration with a
    # missing math prototype would otherwise return int-typed floats without a word.
    flags = ["-O2", "-fPIC", "-w", "-Werror=implicit-function-declaration", "-Werror=int-conversion",
             "-ffp-contract=off", "-include", str(OUT / "wordsize_shim.h"),
             f"-I{rtw}", f"-I{shared}"]
    sources = [mdlapp_c] + sorted(shared.glob("*.c")) + [table_c]
    objs = []
    for src in sources:
        obj = OUT / (src.stem + ".o")
        r = subprocess.run([args.cc, *flags, "-c", str(src), "-o", str(obj)], capture_output=True, text=True)
        if r.returncode:
            sys.stderr.write(r.stderr)
            raise SystemExit(f"[build] compile failed: {src.name}")
        objs.append(str(obj))
    lib = OUT / "libx1exc_sil.so"
    r = subprocess.run([args.cc, "-shared", "-o", str(lib), *objs, "-lm"], capture_output=True, text=True)
    if r.returncode:
        sys.stderr.write(r.stderr)
        raise SystemExit("[build] link failed")
    undefined = subprocess.run(["nm", "-D", "--undefined-only", str(lib)], capture_output=True, text=True).stdout
    undefined = [l.split()[-1] for l in undefined.splitlines()
                 if l.strip() and not l.strip().startswith("w ") and "GLIBC" not in l]
    if undefined:
        raise SystemExit(f"[build] unresolved symbols: {undefined}")

    def git(*a):
        # --no-optional-locks: plain `git status` may rewrite X1Exc/.git/index to refresh
        # its stat cache. That is a write into a repo we treat as read-only.
        r = subprocess.run(["git", "--no-optional-locks", "-C", str(args.x1exc), *a],
                           capture_output=True, text=True)
        return r.stdout.strip() if r.returncode == 0 else None

    manifest = {
        "x1exc_dir": str(args.x1exc),
        "x1exc_commit": git("rev-parse", "HEAD"),
        "x1exc_dirty": bool(git("status", "--porcelain", "--", "Asw/GeneratedCode")),
        "codegen_stamp": re.search(r"C/C\+\+ source code generated on\s*:\s*(.+)",
                                   (rtw / "MdlApp.h").read_text(encoding="latin-1")).group(1).strip(),
        "compiler": subprocess.run([args.cc, "--version"], capture_output=True, text=True).stdout.splitlines()[0],
        "flags": flags,
        "leaves": n_by_root,
        "enums": {k: v for k, v in enums.items()},
        "inhibit_bits": bits,
        "inhibit_masks": masks,
        "chart_states": chart_states,
        "calib_chart_names_not_in_enum": calib_name_mismatch,
        "internals": [[n, t] for n, t, _ in INTERNALS],
        "sample_time_s": 0.01,
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2))
    print(f"[build] {lib}")
    print(f"[build] X1Exc {manifest['x1exc_commit'][:8] if manifest['x1exc_commit'] else '?'}"
          f"{' (DIRTY)' if manifest['x1exc_dirty'] else ''}, generated {manifest['codegen_stamp']}")
    print(f"[build] leaves: " + ", ".join(f"{k}={v}" for k, v in n_by_root.items())
          + f"; enums: {len(enums)}; inhibit bits: {len(bits)}, "
          f"AUTO mask 0x{masks['AUTO_INHIBIT_MASK']['value']:04X}")


if __name__ == "__main__":
    main()
