#!/usr/bin/env python3
"""
build.py -- compile the X1Exc firmware (MdlApp) into a host shared library for SIL.

READS X1Exc, NEVER WRITES IT. Every output goes to <xpanner-sim>/build/sil/.

WHAT IT PRODUCES
    build/sil/libx1exc_sil.so   MdlApp.c + _sharedutils/*.c + a generated signal table
    build/sil/sil_table.c       the generated table (kept for inspection)
    build/sil/manifest.json     X1Exc commit, compiler, leaf counts, enums, inhibit bits

THE SIGNAL TABLE, AND WHY THE COMPILER CHECKS IT
    ExtU_MdlApp_T alone has 91 fields and several nested bus types; ParLocal_t is bigger.
    Hand-writing ctypes structures for that is how a SIL harness ends up feeding the
    wrong byte to the right-looking name. So the headers are parsed, every leaf field is
    flattened to a dotted path ("tarPanelData.row1Id", "parKin.lenArm"), and each leaf is
    emitted with offsetof() + a _Static_assert on its sizeof. If the parser ever
    misreads a type, the table does not compile. (The first thing this caught while
    being written: TarPanelData_t.row1Id is uint32, not the uint8 the analysis said.)

WORD SIZE
    The ERT code was generated for a 32-bit target and #errors if long is not 32-bit.
    rtwtypes.h maps every fixed-width type to char/short/int and no generated .c uses
    long or ulong_T, so the guard is the only thing that sees the difference. A forced
    include redefines LONG_MAX/ULONG_MAX for the guard only. The sanctioned fix is
    "Enable portable word sizes" at code generation time; ask David if this ever matters.

USAGE
    python3 sil/build.py [--x1exc /home/ubuntu/jude/X1Exc] [--cc gcc]
"""
import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_X1EXC = Path(os.environ.get("X1EXC_DIR", REPO.parent / "X1Exc"))
OUT = REPO / "build" / "sil"

PRIM = {  # rtwtypes name -> (type code, size in bytes)
    "int8_T": ("b", 1), "uint8_T": ("B", 1), "boolean_T": ("?", 1), "char_T": ("b", 1),
    "int16_T": ("h", 2), "uint16_T": ("H", 2),
    "int32_T": ("i", 4), "uint32_T": ("I", 4), "int_T": ("i", 4), "uint_T": ("I", 4),
    "real32_T": ("f", 4), "real64_T": ("d", 8), "real_T": ("d", 8), "time_T": ("d", 8),
}
ROOTS = [  # (prefix, C type, C object)
    ("u", "ExtU_MdlApp_T", "MdlApp_U"),
    ("y", "ExtY_MdlApp_T", "MdlApp_Y"),
    ("par", "ParLocal_t", "parLocalTest"),
]

SHIM = """/* generated by sil/build.py -- see WORD SIZE in its docstring */
#include <limits.h>
#undef ULONG_MAX
#undef LONG_MAX
#define ULONG_MAX 0xFFFFFFFFUL
#define LONG_MAX  0x7FFFFFFFL
"""


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def parse_headers(header_files):
    structs, enums = {}, {}
    for hf in header_files:
        t = strip_comments(hf.read_text(encoding="latin-1"))
        for m in re.finditer(r"typedef\s+struct\s*\w*\s*\{(.*?)\}\s*(\w+)\s*;", t, re.S):
            body, name = m.group(1), m.group(2)
            fields = []
            for stmt in body.split(";"):
                stmt = " ".join(stmt.split())
                if not stmt or ":" in stmt:  # bitfields live only in DW, never in U/Y/par
                    continue
                fm = re.match(r"^(?:const )?(\w+) (\w+)((?:\[\d+\])*)$", stmt)
                if not fm:
                    # e.g. the nested union in rt_nonfinite.h. Harmless unless a root
                    # actually reaches this type, and flatten() refuses loudly if it does.
                    fields = None
                    break
                dims = [int(d) for d in re.findall(r"\[(\d+)\]", fm.group(3))]
                fields.append((fm.group(1), fm.group(2), dims))
            structs[name] = fields
        for m in re.finditer(r"typedef\s+enum\s*\{(.*?)\}\s*(\w+)\s*;", t, re.S):
            vals, nxt = {}, 0
            for item in m.group(1).split(","):
                item = item.strip()
                if not item:
                    continue
                if "=" in item:
                    k, v = [x.strip() for x in item.split("=", 1)]
                    v = re.sub(r"\(\w+\)", "", v)  # strip casts
                    nxt = int(v.rstrip("uUlL"), 0)
                else:
                    k = item
                vals[k] = nxt
                nxt += 1
            enums[m.group(2)] = vals
    return structs, enums


def flatten(structs, enums, ctype, path=""):
    """Yield (dotted path, C designator, type code, element count, element C type)."""
    if structs[ctype] is None:
        raise SystemExit(f"[build] {ctype} (reached via {path or 'root'}) has a body this parser cannot read")
    for ftype, name, dims in structs[ctype]:
        count = 1
        for d in dims:
            count *= d
        p = f"{path}.{name}" if path else name
        if ftype in PRIM or ftype in enums:
            code = PRIM[ftype][0] if ftype in PRIM else "e"
            yield p, p, code, count, ftype
        elif ftype in structs:
            if dims:
                if len(dims) != 1:
                    raise SystemExit(f"[build] multi-dim struct array {p} not supported")
                for i in range(dims[0]):
                    yield from flatten(structs, enums, ftype, f"{p}[{i}]")
            else:
                yield from flatten(structs, enums, ftype, p)
        else:
            raise SystemExit(f"[build] unknown type {ftype} at {p}")


def inhibit_bits(mdlapp_c):
    t = mdlapp_c.read_text(encoding="latin-1")
    bits = {m.group(1): int(m.group(2)) for m in
            re.finditer(r"'\s*(BIT_\w+)\s*=\s*bitshift\(uint32\(1\),\s*(\d+)\)", t)}
    masks = {}
    for mask in ("AUTO_INHIBIT_MASK", "CALIB_INHIBIT_MASK"):
        names = re.findall(mask + r"\s*=\s*bitor\(" + mask + r",\s*(BIT_\w+)\)", t)
        masks[mask] = {"bits": sorted(set(names), key=lambda n: bits[n]),
                       "value": sum(1 << bits[n] for n in set(names))}
    return bits, masks


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--x1exc", type=Path, default=DEFAULT_X1EXC)
    ap.add_argument("--cc", default=os.environ.get("CC", "gcc"))
    args = ap.parse_args()

    gen = args.x1exc / "Asw" / "GeneratedCode"
    rtw, shared = gen / "MdlApp_ert_rtw", gen / "slprj" / "ert" / "_sharedutils"
    mdlapp_c = rtw / "MdlApp.c"
    if not mdlapp_c.is_file():
        raise SystemExit(f"[build] {mdlapp_c} not found (set --x1exc or X1EXC_DIR)")
    OUT.mkdir(parents=True, exist_ok=True)

    structs, enums = parse_headers(sorted(shared.glob("*.h")) + [rtw / "MdlApp.h"])
    bits, masks = inhibit_bits(mdlapp_c)
    code_auto = re.search(r"\(\(uint32_T\)status\)\s*&\s*\(\(uint32_T\)(\d+)U\)", mdlapp_c.read_text(encoding="latin-1"))
    if code_auto and int(code_auto.group(1)) != masks["AUTO_INHIBIT_MASK"]["value"]:
        raise SystemExit(f"[build] AUTO_INHIBIT_MASK from comments {masks['AUTO_INHIBIT_MASK']['value']} "
                         f"!= literal in code {code_auto.group(1)}")

    (OUT / "wordsize_shim.h").write_text(SHIM)
    lines = [
        "/* GENERATED by sil/build.py from X1Exc headers. Do not edit. */",
        "#include <stddef.h>", '#include "MdlApp.h"', "",
        "typedef struct { const char *path; unsigned char base; unsigned char type;",
        "                 unsigned int count; unsigned long offset; unsigned int elem_size; } sil_sig_t;",
        "",
        "const sil_sig_t sil_signals[] = {",
    ]
    asserts, n_by_root = [], {}
    for ri, (prefix, ctype, obj) in enumerate(ROOTS):
        n = 0
        for path, desig, code, count, ftype in flatten(structs, enums, ctype):
            size = PRIM[ftype][1] if ftype in PRIM else 4
            lines.append(f'  {{"{prefix}.{path}", {ri}, \'{code}\', {count}u, '
                         f"offsetof({ctype}, {desig}), {size}u}},")
            asserts.append(f"_Static_assert(sizeof((({ctype}*)0)->{desig}) == {count * size}u, "
                           f'"{prefix}.{path}");')
            n += 1
        n_by_root[prefix] = n
    lines += ["};", "const unsigned int sil_signal_count = sizeof(sil_signals)/sizeof(sil_signals[0]);", ""]
    lines += [f"_Static_assert(sizeof({e}) == 4u, \"enum {e} is not int-sized\");" for e in enums]
    lines += asserts + [
        "",
        "void *sil_base(unsigned int b) {",
        "  switch (b) { case 0: return &MdlApp_U; case 1: return &MdlApp_Y; case 2: return &parLocalTest; }",
        "  return 0;",
        "}",
        "unsigned long sil_base_size(unsigned int b) {",
        "  switch (b) { case 0: return sizeof(MdlApp_U); case 1: return sizeof(MdlApp_Y); case 2: return sizeof(parLocalTest); }",
        "  return 0;",
        "}",
    ]
    table_c = OUT / "sil_table.c"
    table_c.write_text("\n".join(lines) + "\n")

    flags = ["-O2", "-fPIC", "-w", "-ffp-contract=off", "-include", str(OUT / "wordsize_shim.h"),
             f"-I{rtw}", f"-I{shared}"]
    sources = [mdlapp_c] + sorted(shared.glob("*.c")) + [table_c]
    objs = []
    for src in sources:
        obj = OUT / (src.stem + ".o")
        r = subprocess.run([args.cc, *flags, "-c", str(src), "-o", str(obj)], capture_output=True, text=True)
        if r.returncode:
            sys.stderr.write(r.stderr)
            raise SystemExit(f"[build] compile failed: {src.name}")
        objs.append(str(obj))
    lib = OUT / "libx1exc_sil.so"
    r = subprocess.run([args.cc, "-shared", "-o", str(lib), *objs, "-lm"], capture_output=True, text=True)
    if r.returncode:
        sys.stderr.write(r.stderr)
        raise SystemExit("[build] link failed")
    undefined = subprocess.run(["nm", "-D", "--undefined-only", str(lib)], capture_output=True, text=True).stdout
    undefined = [l.split()[-1] for l in undefined.splitlines()
                 if l.strip() and not l.strip().startswith("w ") and "GLIBC" not in l]
    if undefined:
        raise SystemExit(f"[build] unresolved symbols: {undefined}")

    def git(*a):
        # --no-optional-locks: plain `git status` may rewrite X1Exc/.git/index to refresh
        # its stat cache. That is a write into a repo we treat as read-only.
        r = subprocess.run(["git", "--no-optional-locks", "-C", str(args.x1exc), *a],
                           capture_output=True, text=True)
        return r.stdout.strip() if r.returncode == 0 else None

    manifest = {
        "x1exc_dir": str(args.x1exc),
        "x1exc_commit": git("rev-parse", "HEAD"),
        "x1exc_dirty": bool(git("status", "--porcelain", "--", "Asw/GeneratedCode")),
        "codegen_stamp": re.search(r"C/C\+\+ source code generated on\s*:\s*(.+)",
                                   (rtw / "MdlApp.h").read_text(encoding="latin-1")).group(1).strip(),
        "compiler": subprocess.run([args.cc, "--version"], capture_output=True, text=True).stdout.splitlines()[0],
        "flags": flags,
        "leaves": n_by_root,
        "enums": {k: v for k, v in enums.items()},
        "inhibit_bits": bits,
        "inhibit_masks": masks,
        "sample_time_s": 0.01,
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2))
    print(f"[build] {lib}")
    print(f"[build] X1Exc {manifest['x1exc_commit'][:8] if manifest['x1exc_commit'] else '?'}"
          f"{' (DIRTY)' if manifest['x1exc_dirty'] else ''}, generated {manifest['codegen_stamp']}")
    print(f"[build] leaves: " + ", ".join(f"{k}={v}" for k, v in n_by_root.items())
          + f"; enums: {len(enums)}; inhibit bits: {len(bits)}, "
          f"AUTO mask 0x{masks['AUTO_INHIBIT_MASK']['value']:04X}")


if __name__ == "__main__":
    main()
